### ISSUE TITLE
:bug: "old_new" data point not set?

### ISSUE THREAD

**Issue by enryH** [Proteobench/ProteoBench#288]
**Describe the bug**
Upload is not working

**To Reproduce**
DDA_Quant_ion, 

**Expected behavior**
Upload either accepted or denied.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: latest main + PR

**Additional context**

```python
File "C:\Users\kzl465\Anaconda3\envs\proteobench\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 667, in <module>
    StreamlitUI()
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 56, in __init__
    self._main_page()
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 157, in _main_page
    self._populate_results()
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 217, in _populate_results
    self.generate_results("", None, None, False, None)
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 598, in generate_results
    pr_url = self.make_submission_webinterface(
File "C:\Users\kzl465\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 363, in make_submission_webinterface
    st.session_state[self.variables_dda_quant.all_datapoints]["old_new"] == "new"
```

Somehow it seems as `add_current_data_point` is not called anymore.

**Comment by RobbinBouwmeester** [comment]
Issue was that after uploading a param file, the df resets, still not sure why. Need to fix that in the future.

New copy of the dataframe works: #289

**Comment by enryH** [comment]
perfect! Thanks.

**Comment by enryH** [comment]
Hmm. I get a new error now:

```bash
INFO:Writing the json to: C:\Users\user\AppData\Local\Temp\tmpyfi6_kwk\results.json                           
Following Github server redirection from /repos/Proteobot/Results_Module2_quant_DDA to /repositories/594        032348                                                                                                          
INFO:Following Github server redirection from /repos/Proteobot/Results_Module2_quant_DDA to /repositorie        s/594032348                                                                                                     
Following Github server redirection from /repos/Proteobot/Results_quant_ion_DDA/branches/master to /repo        s/Proteobot/Results_quant_ion_DDA/branches/main
INFO:Following Github server redirection from /repos/Proteobot/Results_quant_ion_DDA/branches/master to 
DA/branches/master to /repos/Proteobot/Results_quant_ion_DDA/branches/main
2024-04-25 11:04:41.995 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\proteobench\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 667, in <module> 
    StreamlitUI()
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 56, in __init__  
    self._main_page()
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 157, in _main_page
    self._populate_results()
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 217, in _populate_results
    self.generate_results("", None, None, False, None)
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 598, in generate_results
    pr_url = self.make_submission_webinterface(
  File "C:\Users\user\Documents\repos\ProteoBench\webinterface\pages\DDA_Quant_ion.py", line 368, in make_submission_webinterface
    self.ionmodule.write_intermediate_raw(
  File "C:\Users\user\Documents\repos\ProteoBench\proteobench\modules\dda_quant_base\module.py", line 219, in 
write_intermediate_raw
    input_df.to_csv(os.path.join(path_write, "input_df.csv"))
AttributeError: 'NoneType' object has no attribute 'to_csv'
```

I guess I will need to create a new issue. It's really tricky to debug the submission process...

**Comment by enryH** [comment]
Create a new issue: https://github.com/Proteobench/ProteoBench/issues/290
